# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpe.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\trpe.proto\x12\x03rpe\"+\n\x08Response\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"2\n\x13RPEVerificationInfo\x12\x1b\n\x13rpeVerificationInfo\x18\x01 \x01(\t\".\n\x11RequiredRPENumber\x12\x19\n\x11requiredRPENumber\x18\x01 \x01(\x05\":\n\rRpeIdAndQuote\x12\r\n\x05rpeId\x18\x01 \x01(\t\x12\x1a\n\x12\x62\x61se64EncodedQuote\x18\x02 \x01(\t\"\x16\n\x05RpeId\x12\r\n\x05rpeId\x18\x01 \x01(\t\"?\n\x12VerificationResult\x12\r\n\x05rpeId\x18\x01 \x01(\t\x12\x1a\n\x12verificationResult\x18\x02 \x01(\t\"\x18\n\x06RpeIds\x12\x0e\n\x06rpeIds\x18\x01 \x01(\t\"\'\n\x06\x43\x45Info\x12\r\n\x05jobId\x18\x01 \x01(\t\x12\x0e\n\x06\x63\x65Info\x18\x02 \x01(\t\"\x18\n\x06JobIds\x12\x0e\n\x06jobIds\x18\x01 \x01(\t2\xc1\x03\n\nRpeService\x12\x44\n\x17SendRPEVerificationInfo\x12\x18.rpe.RPEVerificationInfo\x1a\r.rpe.Response\"\x00\x12\x34\n\tQueryRPEs\x12\x16.rpe.RequiredRPENumber\x1a\r.rpe.Response\"\x00\x12\x30\n\tSendQuote\x12\x12.rpe.RpeIdAndQuote\x1a\r.rpe.Response\"\x00\x12)\n\nQueryQuote\x12\n.rpe.RpeId\x1a\r.rpe.Response\"\x00\x12\x42\n\x16SendVerificationResult\x12\x17.rpe.VerificationResult\x1a\r.rpe.Response\"\x00\x12<\n\x1cQueryVerificationFinalResult\x12\x0b.rpe.RpeIds\x1a\r.rpe.Response\"\x00\x12*\n\nSendCEInfo\x12\x0b.rpe.CEInfo\x1a\r.rpe.Response\"\x00\x12,\n\x0cQueryCEsInfo\x12\x0b.rpe.JobIds\x1a\r.rpe.Response\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rpe_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RESPONSE._serialized_start=18
  _RESPONSE._serialized_end=61
  _RPEVERIFICATIONINFO._serialized_start=63
  _RPEVERIFICATIONINFO._serialized_end=113
  _REQUIREDRPENUMBER._serialized_start=115
  _REQUIREDRPENUMBER._serialized_end=161
  _RPEIDANDQUOTE._serialized_start=163
  _RPEIDANDQUOTE._serialized_end=221
  _RPEID._serialized_start=223
  _RPEID._serialized_end=245
  _VERIFICATIONRESULT._serialized_start=247
  _VERIFICATIONRESULT._serialized_end=310
  _RPEIDS._serialized_start=312
  _RPEIDS._serialized_end=336
  _CEINFO._serialized_start=338
  _CEINFO._serialized_end=377
  _JOBIDS._serialized_start=379
  _JOBIDS._serialized_end=403
  _RPESERVICE._serialized_start=406
  _RPESERVICE._serialized_end=855
# @@protoc_insertion_point(module_scope)
