# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ce.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08\x63\x65.proto\x12\x02\x63\x65\"+\n\x08Response\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"\x14\n\x04Info\x12\x0c\n\x04info\x18\x01 \x01(\t\"\x18\n\x06Params\x12\x0e\n\x06params\x18\x01 \x01(\t2Z\n\tCeService\x12$\n\x08SendInfo\x12\x08.ce.Info\x1a\x0c.ce.Response\"\x00\x12\'\n\tQueryInfo\x12\n.ce.Params\x1a\x0c.ce.Response\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ce_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RESPONSE._serialized_start=16
  _RESPONSE._serialized_end=59
  _INFO._serialized_start=61
  _INFO._serialized_end=81
  _PARAMS._serialized_start=83
  _PARAMS._serialized_end=107
  _CESERVICE._serialized_start=109
  _CESERVICE._serialized_end=199
# @@protoc_insertion_point(module_scope)
